name: my_environment
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - joblib=1.4.2
  - fastapi=0.115.0
  - uvicorn=0.31.0
  - pydantic=2.9.2
  - pip
  - pip:
      - pytest==8.3.3
      - requests==2.32.3
      - gunicorn>=21.2.0
